/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_flow_modeld_TNN */

#ifndef _Included_ai_flow_modeld_TNN
#define _Included_ai_flow_modeld_TNN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_flow_modeld_TNN
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ai_flow_modeld_TNN_init
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    createInput
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_createInput
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    createOutput
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_createOutput
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    forward
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_forward__Ljava_util_Map_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    forward
 * Signature: (Ljava/util/Map;Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_forward__Ljava_util_Map_2Ljava_lang_String_2_3F
  (JNIEnv *, jobject, jobject, jstring, jfloatArray);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    forward
 * Signature: (Ljava/util/Map;Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ai_flow_modeld_TNN_forward__Ljava_util_Map_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    forward
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_forward__Ljava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Ljava_nio_ByteBuffer_2Ljava_lang_String_2_3F
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jstring, jfloatArray);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    getOutputBuffer
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ai_flow_modeld_TNN_getOutputBuffer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    getOutput
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ai_flow_modeld_TNN_getOutput__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ai_flow_modeld_TNN
 * Method:    getOutput
 * Signature: (Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_ai_flow_modeld_TNN_getOutput__Ljava_lang_String_2_3F
  (JNIEnv *, jobject, jstring, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
